---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-dev1
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev1
  chart:
    git: git@github.com:Ashishkasaudhan/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: ashishkasaudhan/podinfo
      tag: dev-7xspopal
    replicaCount: 1
    hpa:
      enabled: false
