---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-prod1
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod1
  chart:
    git: git@github.com:Ashishkasaudhan/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: ashishkasaudhan/podinfo
      tag: 0.4.11
    replicaCount: 3
