---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-rc1
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: podinfo-rc1
  chart:
    git: git@github.com:Akasaudhan/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: ashishkasaudhan/podinfo
      tag: stg-tnp5m7yu
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
